#!usr/bin/env bash

# shopt -u dotglob && rm -rf /mnt/c/kkn_folder/project/medience/socket/*

rsync -rv --exclude=**/node_modules/ --exclude=./copytorepo ./* ../../project/medience/socket/

sshpass -p 'ander1234!' rsync -rv --exclude=**/node_modules/ --exclude=./copytorepo ./* root@192.168.88.232:/home/test/