version: "3.8"

services:
  fst:
    image: tianon/true
    container_name: first_server
    depends_on:
      - back
      - front
      - socket
      - publisher
  scnd:
    image: tianon/true
    container_name: second_server
    depends_on:
      - back2
      - front2
      - socket2
      - publisher2

  back:
    image: node:lts
    command: nodemon index.js
    container_name: back
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 3001:3001
    working_dir: /home/
    volumes:
      - ./backend/:/home
      # - /home/node_modules/
    environment:
      HOST: 0.0.0.0
      PORT: 3001
      NODE_ENV: production
      MARIADB_PORT: 3307
      MARIADB_HOST: 192.168.88.234
      MARIADB_USERNAME: share
      MARIADB_PW: 1234
      MARIADB_DATABASE: internal_server
      SOCKET_HOST: 192.168.88.234
      PUBLISHER_HOST: 192.168.88.234

  front:
    image: node:lts
    command: vite --config vite.config.js
    container_name: front
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 5001:5001
    working_dir: /home/
    volumes:
      - ./frontend/:/home
      # - /home/node_modules/
    environment:
      HOST: 0.0.0.0
      PORT: 5001
      NODE_ENV: production
      VITE_API_HOST: 192.168.88.234
      VITE_API_PORT: 3001

  socket:
    image: node:lts
    # command: nodemon index.js
    command: nodemon relay.js
    container_name: socket
    build:
      context: .
      dockerfile: ./socket/Dockerfile
    ports:
      - 10000:10000
    working_dir: /home/
    volumes:
      - ./socket/:/home
      # - /home/node_modules/
    environment:
      HOST: 0.0.0.0
      PORT: 10000
      NODE_ENV: production
      MARIADB_PORT: 3307
      MARIADB_HOST: 192.168.88.234
      MARIADB_USERNAME: share
      MARIADB_PW: 1234
      MARIADB_DATABASE: internal_server
      API_HOST: 192.168.88.234
      API_PORT: 3001
      PORT_GAP: 20000

  publisher:
    image: node:lts
    command: nodemon index.js
    container_name: publisher
    build:
      context: .
      dockerfile: ./relay/Dockerfile
    ports:
      - 20000:20000
      - 40000:40000
    working_dir: /home/
    volumes:
      - ./relay/:/home
      # - /home/node_modules/
    environment:
      HOST: 0.0.0.0
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 20000
      NODE_ENV: production
      MARIADB_PORT: 3307
      MARIADB_HOST: 192.168.88.234
      MARIADB_USERNAME: share
      MARIADB_PW: 1234
      MARIADB_DATABASE: internal_server
      PORT_GAP: 20000
      IP_ADDRESS: 192.168.88.234

  back2:
    image: node:lts
    command: nodemon index.js
    container_name: back2
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 3002:3002
    working_dir: /home/
    volumes:
      - ./backend/:/home
      # - /home/node_modules/
    environment:
      HOST: 0.0.0.0
      PORT: 3002
      NODE_ENV: production
      MARIADB_PORT: 3307
      MARIADB_HOST: 192.168.88.234
      MARIADB_USERNAME: share
      MARIADB_PW: 1234
      MARIADB_DATABASE: internal_server
      SOCKET_HOST: 192.168.88.234
      PUBLISHER_HOST: 192.168.88.234

  front2:
    image: node:lts
    command: vite --config vite.config.js
    container_name: front2
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 5002:5002
    working_dir: /home/
    volumes:
      - ./frontend/:/home
      # - /home/node_modules/
    environment:
      HOST: 0.0.0.0
      PORT: 5002
      NODE_ENV: production
      VITE_API_HOST: 192.168.88.234
      VITE_API_PORT: 3002

  socket2:
    image: node:lts
    # command: nodemon index.js
    command: nodemon relay.js
    container_name: socket2
    build:
      context: .
      dockerfile: ./socket/Dockerfile
    ports:
      - 10001:10001
    working_dir: /home/
    volumes:
      - ./socket/:/home
      # - /home/node_modules/
    environment:
      HOST: 0.0.0.0
      PORT: 10001
      NODE_ENV: production
      MARIADB_PORT: 3307
      MARIADB_HOST: 192.168.88.234
      MARIADB_USERNAME: share
      MARIADB_PW: 1234
      MARIADB_DATABASE: internal_server
      API_HOST: 192.168.88.234
      API_PORT: 3002
      PORT_GAP: 20000

  publisher2:
    image: node:lts
    command: nodemon index.js
    container_name: publisher2
    build:
      context: .
      dockerfile: ./relay/Dockerfile
    ports:
      - 20001:20001
      - 40001:40001
    working_dir: /home/
    volumes:
      - ./relay/:/home
      # - /home/node_modules/
    environment:
      HOST: 0.0.0.0
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 20001
      NODE_ENV: production
      MARIADB_PORT: 3307
      MARIADB_HOST: 192.168.88.234
      MARIADB_USERNAME: share
      MARIADB_PW: 1234
      MARIADB_DATABASE: internal_server
      PORT_GAP: 20000
      IP_ADDRESS: 192.168.88.234
